import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as vscode from 'vscode';

const COMMAND_SETUP = 'asciidoctorNumberedCaptions.setupMvp';

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(vscode.commands.registerCommand(COMMAND_SETUP, async () => {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      void vscode.window.showErrorMessage('Workspace が開かれていません。フォルダを開いてから実行してください。');
      return;
    }

    const rootPath = workspaceFolder.uri.fsPath;
    const pluginDir = path.join(rootPath, '.asciidoctor', 'lib');
    const pluginFile = path.join(pluginDir, 'numbered-captions.js');

    const config = vscode.workspace.getConfiguration('asciidoctorNumberedCaptions', workspaceFolder.uri);
    const defaultNumbering = config.get<string>('defaultNumbering', 'chaptered');
    const chapterLevel = config.get<number>('chapterLevel', 1);

    await fs.mkdir(pluginDir, { recursive: true });

    const pluginSource = `/* Auto-generated by asciidoctor-numbered-captions-vscode */
module.exports = function (registry) {
  const ext = require('asciidoctor-numbered-captions')
  if (typeof ext.register === 'function') {
    return ext.register(registry, {
      defaultNumbering: ${JSON.stringify(defaultNumbering)},
      chapterLevel: ${JSON.stringify(chapterLevel)}
    })
  }
  if (typeof ext === 'function') {
    return ext(registry)
  }
  throw new Error('asciidoctor-numbered-captions module shape is unsupported')
}
`;

    await fs.writeFile(pluginFile, pluginSource, 'utf8');

    const asciidocConfig = vscode.workspace.getConfiguration('asciidoc', workspaceFolder.uri);
    await asciidocConfig.update('extensions.registerWorkspaceExtensions', true, vscode.ConfigurationTarget.WorkspaceFolder);

    const existingAttrs = asciidocConfig.get<Record<string, string>>('preview.asciidoctorAttributes', {});
    const mergedAttrs: Record<string, string> = {
      ...existingAttrs,
      sectnums: existingAttrs.sectnums ?? '',
      stem: existingAttrs.stem ?? 'latexmath',
      'numbered-captions-numbering': existingAttrs['numbered-captions-numbering'] ?? defaultNumbering
    };
    await asciidocConfig.update('preview.asciidoctorAttributes', mergedAttrs, vscode.ConfigurationTarget.WorkspaceFolder);

    const modulePath = path.join(rootPath, 'node_modules', 'asciidoctor-numbered-captions');
    let dependencyInstalled = true;
    try {
      await fs.access(modulePath);
    } catch {
      dependencyInstalled = false;
    }

    if (dependencyInstalled) {
      void vscode.window.showInformationMessage('MVP セットアップ完了: numbered-captions をプレビューで利用できます。');
      return;
    }

    const install = 'Install dependency in terminal';
    const selected = await vscode.window.showWarningMessage(
      'asciidoctor-numbered-captions が未インストールです。npm install を実行してください。',
      install
    );

    if (selected === install) {
      const terminal = vscode.window.createTerminal({
        name: 'Install asciidoctor-numbered-captions',
        cwd: rootPath
      });
      terminal.show(true);
      terminal.sendText('npm i YoshihideShirai/asciidoctor-numbered-captions');
    }
  }));
}

export function deactivate(): void {
  // no-op
}
