import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as vscode from 'vscode';

const COMMAND_SETUP = 'asciidoctorNumberedCaptions.setupMvp';

function buildPluginSource(defaultNumbering: string, chapterLevel: number): string {
  return `/* Auto-generated by asciidoctor-numbered-captions-vscode */
module.exports = function (registry) {
  const DEFAULTS = {
    numbering: ${JSON.stringify(defaultNumbering)},
    chapterLevel: ${JSON.stringify(chapterLevel)},
    labels: {
      image: 'Figure',
      table: 'Table',
      stem: 'Equation'
    },
    labelAttributes: {
      image: 'figure-caption',
      table: 'table-caption',
      stem: 'equation-caption'
    }
  }

  registry.treeProcessor(function () {
    this.process(function (doc) {
      const mode = (doc.getAttribute('numbered-captions-numbering') || DEFAULTS.numbering || 'standard').toString()
      if (mode !== 'chaptered') {
        return doc
      }

      const chapterLevel = parseInt((doc.getAttribute('numbered-captions-chapter-level') || DEFAULTS.chapterLevel || 1).toString(), 10)
      const safeChapterLevel = Number.isInteger(chapterLevel) && chapterLevel >= 1 ? chapterLevel : 1

      const labels = {
        image: (doc.getAttribute(DEFAULTS.labelAttributes.image) || DEFAULTS.labels.image).toString(),
        table: (doc.getAttribute(DEFAULTS.labelAttributes.table) || DEFAULTS.labels.table).toString(),
        stem: (doc.getAttribute(DEFAULTS.labelAttributes.stem) || doc.getAttribute('stem-caption') || DEFAULTS.labels.stem).toString()
      }

      const counters = new Map()
      let chapterCounter = 0

      function nextCaptionNumber(chapter, context) {
        const key = chapter + ':' + context
        const current = counters.get(key) || 0
        const next = current + 1
        counters.set(key, next)
        return next
      }

      function applyCaption(block, chapter) {
        const context = block.getContext()
        if (!['image', 'table', 'stem'].includes(context)) {
          return
        }
        const title = block.getTitle && block.getTitle()
        if (!title) {
          return
        }

        const seq = nextCaptionNumber(chapter, context)
        const label = labels[context] || context
        block.setAttribute('caption', label + ' ' + chapter + '-' + seq + '. ')
      }

      function walkBlocks(blocks, currentChapter) {
        for (const block of blocks) {
          if (block.getContext && block.getContext() === 'section') {
            const level = block.getLevel ? block.getLevel() : 1
            let childChapter = currentChapter

            if (level === safeChapterLevel) {
              chapterCounter += 1
              childChapter = String(chapterCounter)
            }

            const nestedBlocks = block.getBlocks ? block.getBlocks() : []
            walkBlocks(nestedBlocks, childChapter)
            continue
          }

          applyCaption(block, currentChapter)

          const nestedBlocks = block.getBlocks ? block.getBlocks() : []
          if (nestedBlocks.length > 0) {
            walkBlocks(nestedBlocks, currentChapter)
          }
        }
      }

      walkBlocks(doc.getBlocks ? doc.getBlocks() : [], '1')
      return doc
    })
  })
}
`;
}

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(vscode.commands.registerCommand(COMMAND_SETUP, async () => {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      void vscode.window.showErrorMessage('Workspace が開かれていません。フォルダを開いてから実行してください。');
      return;
    }

    const rootPath = workspaceFolder.uri.fsPath;
    const pluginDir = path.join(rootPath, '.asciidoctor', 'lib');
    const pluginFile = path.join(pluginDir, 'numbered-captions.js');

    const config = vscode.workspace.getConfiguration('asciidoctorNumberedCaptions', workspaceFolder.uri);
    const defaultNumbering = config.get<string>('defaultNumbering', 'chaptered');
    const chapterLevel = config.get<number>('chapterLevel', 1);

    await fs.mkdir(pluginDir, { recursive: true });
    await fs.writeFile(pluginFile, buildPluginSource(defaultNumbering, chapterLevel), 'utf8');

    const asciidocConfig = vscode.workspace.getConfiguration('asciidoc', workspaceFolder.uri);
    await asciidocConfig.update('extensions.registerWorkspaceExtensions', true, vscode.ConfigurationTarget.WorkspaceFolder);

    const existingAttrs = asciidocConfig.get<Record<string, string>>('preview.asciidoctorAttributes', {});
    const mergedAttrs: Record<string, string> = {
      ...existingAttrs,
      sectnums: existingAttrs.sectnums ?? '',
      stem: existingAttrs.stem ?? 'latexmath',
      'numbered-captions-numbering': existingAttrs['numbered-captions-numbering'] ?? defaultNumbering,
      'numbered-captions-chapter-level': existingAttrs['numbered-captions-chapter-level'] ?? String(chapterLevel)
    };
    await asciidocConfig.update('preview.asciidoctorAttributes', mergedAttrs, vscode.ConfigurationTarget.WorkspaceFolder);

    void vscode.window.showInformationMessage(
      'MVP セットアップ完了: .asciidoctor/lib/numbered-captions.js を生成し、workspace extension registration を有効化しました。'
    );
  }));
}

export function deactivate(): void {
  // no-op
}
